language: ruby
rvm:
- 2.5.0
services:
- postgresql
script:
- bundle install
- bin/rails db:create
- bin/rails db:migrate
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
    # secure: RHEOkxv2W63jAJQURQjKjztHxjQZBtmajnpivjFoBLz/CgCz8st9HAfPRB2Sqq0HRU988aicaXUQ0P02GpDqC7yP5lTyUALrNKUjJWhisZFMqNGfiETqX7HziXj0LSgF/O6boFkih9B79+F5XDXZPJbfaYArh7rZEIgwu7QIj9BmYoHvKgYhL+eCHSZT9wyHlVHeUbp6EZ5+dLvqihqx7z6m1Z/QhioYlT/YmAIwrXBdMOjUsiTF4wMeygaM0axtF86t8SDoT2icFJOd/AJ49WPkeT9f77EJtz3CeRDqY+p1lYeH0NqG1ZeSyLX6whlpGl/UilmObSNacC3P3qU2uF15oCBNkyYM6tF2UMPbbGgn5ZpZwJG4HmCehxJ5nCQ/8gW2Z2C+VEEiksn8tMrB7/EZ/UTCVCGMm/sIaVjxMljqqNVO1RRxTKIAnL9tdiSaLNpwe5EztumXeyPctePqAeJNcQgFbPDzXrXbRKte+HbxF95cq6JnrrUhMH/e2gn3WX43qN7s/UIjPkZ+MwF/Oz/zn58gSGaGg3C1yRq5pfVLycZ3ZlV7KWWjPnE+ADUKFLLPVYnq482/MlzUs3nt0yv/tJf39hECBhpqX6yRQdZb5a1kQQhfIz0S5uybr20JSDtnH8MCm/EYO1+aQwEvjnBirWVCoXgJlXXArFrxUSA=
    secure: oq/6pRuu49pfMOFtwM4OX4A1VoUQ6704Fm2DIn5P2zBXFBnrd4jgFu+lQ2V0zyp8j0EM4P6u1Bws8Zkdiuu+XMTyLiHUxZSG90iFnZXeklsm3V/GRw0Tm8AiuWe3CTZZNe3J1k3LFQzWKayeRbxbyuFPqkqMKXVSaLKMblUCBYcpRRqtd48OqmJd1cjzqv9liG6s2RxwFOwpJ2aqYYG3tzLZr4S9n1DTg7c+3X7W/eqIRP0aDhaAIBrYINQd9PiwLs/68mpvDdUJIXavBGxsIIUm0Ou3+sDiT8yHgljcU9yY6g4ISfSc/hn4czIRv1w+kUQszG635RuYAQ2LBgBDWLATS7ynC3J5PpEj6gB0p0lEWlM1HFaZG5SKfykbZnSS0RaOZg8RMZ6ZABREeUuu/3CIW3R0DwhjgZxE0Kog9gtkruSdKgz1WmRYLa76o+yta4e9U5ig0Ji6HWm0wL9oA6Ftg51ENOybyEfBI39EqMWk9mYtH4jU84qHa8mgOGRQwB3M0KbPLVXvutKZWMN68ek0c13YhuhfRs0gVt/yCD47ZJYk4uZNki/CW/OgT9vZMYrdofGtLO3C9fpyAuemiOmiubByNg4aNd7YmdMQWVUqS37HVEznWXV026jCma30eogGzJDYqVAx4VMTF5QiJf4H91wswt4TAJJxxf0EeFk=
  app: acebook-connectu
  on:
    repo: dtrts/acebook-ConnectU
  run:
  - rake db:migrate
  - restart