language: ruby
rvm:
- 2.5.0
services:
- postgresql
script:
- bundle install
- bin/rails db:create
- bin/rails db:migrate
- bundle exec rspec

deploy:
  provider: heroku
  api_key:
    secure: RHEOkxv2W63jAJQURQjKjztHxjQZBtmajnpivjFoBLz/CgCz8st9HAfPRB2Sqq0HRU988aicaXUQ0P02GpDqC7yP5lTyUALrNKUjJWhisZFMqNGfiETqX7HziXj0LSgF/O6boFkih9B79+F5XDXZPJbfaYArh7rZEIgwu7QIj9BmYoHvKgYhL+eCHSZT9wyHlVHeUbp6EZ5+dLvqihqx7z6m1Z/QhioYlT/YmAIwrXBdMOjUsiTF4wMeygaM0axtF86t8SDoT2icFJOd/AJ49WPkeT9f77EJtz3CeRDqY+p1lYeH0NqG1ZeSyLX6whlpGl/UilmObSNacC3P3qU2uF15oCBNkyYM6tF2UMPbbGgn5ZpZwJG4HmCehxJ5nCQ/8gW2Z2C+VEEiksn8tMrB7/EZ/UTCVCGMm/sIaVjxMljqqNVO1RRxTKIAnL9tdiSaLNpwe5EztumXeyPctePqAeJNcQgFbPDzXrXbRKte+HbxF95cq6JnrrUhMH/e2gn3WX43qN7s/UIjPkZ+MwF/Oz/zn58gSGaGg3C1yRq5pfVLycZ3ZlV7KWWjPnE+ADUKFLLPVYnq482/MlzUs3nt0yv/tJf39hECBhpqX6yRQdZb5a1kQQhfIz0S5uybr20JSDtnH8MCm/EYO1+aQwEvjnBirWVCoXgJlXXArFrxUSA=
  app: acebook-connectu
  on:
    repo: dtrts/acebook-ConnectU
  run:
    - "rake db:migrate"
    - restart
